const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert");

const root = __dirname;
const css = fs.readFileSync(path.join(root, "content-sections.css"), "utf8");
const refreshCss = fs.readFileSync(path.join(root, "design-refresh.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "script.js"), "utf8");

const newsSectionBlock = css.match(/\.news-section\s*\{[^}]*\}/)?.[0] || "";
const pageIndicatorBlock = refreshCss.match(/\.page-indicator\s*\{[^}]*\}/)?.[0] || "";

assert(!/height:\s*100s?vh/.test(newsSectionBlock), "news section must not be fixed to the viewport height");
assert(/\.content-section\s*\{[^}]*overflow:\s*visible/s.test(css), "content sections should allow oversized content to remain visible");
assert(script.includes("canScrollWithinCurrentSection"), "wheel snapping should allow normal scroll inside oversized sections");
assert(!/display:\s*none\s*!important/.test(pageIndicatorBlock), "page indicators should remain visible for hero slide and section orientation");
assert(/scroll-snap-type:\s*y\s+mandatory/.test(refreshCss), "full-page vertical snap scrolling should remain enabled");
assert(/const enableSectionSnap\s*=\s*true/.test(script), "section snap wheel controller should remain enabled");
assert(/\.hero-copy(?:\s+h1)?[\s\S]*?color:\s*(?:#fff|#ffffff|var\(--color-page\))/.test(refreshCss), "hero copy should use a light color on the dark image background");
assert(/\.group-heading\s+h2[\s\S]*?color:\s*(?:#fff|#ffffff|var\(--color-page\))/.test(refreshCss), "hero menu group titles should use a light color on glass cards");
assert(/\.group-heading\s*\{[\s\S]*?border-color:\s*transparent/.test(refreshCss), "hero menu group headings should be visually distinct from clickable menu cards");
assert(/\.group-heading\s*\{[\s\S]*?box-shadow:\s*none/.test(refreshCss), "hero menu group headings should not use the same button-like shadow as menu cards");
assert((html.match(/class="hero-bg/g) || []).length === 7, "hero slider should keep the existing 3 images and add 4 selected generated images");
assert((html.match(/data-hero-indicator=/g) || []).length === 7, "hero slide indicators should match all 7 hero backgrounds");
assert(refreshCss.includes("hero-deep-green-sustainability-clean.png"), "clean deep green generated hero should be wired into the fourth slider slot");
assert(!/hero-bg\[data-bg="3"\][\s\S]*?hero-deep-green-sustainability\.png/.test(refreshCss), "fourth hero slide should not use the infographic-heavy deep green image");
assert(refreshCss.includes("hero-blue-data-intelligence.png"), "blue data generated hero should be wired into the slider");
assert(!refreshCss.includes("hero-white-minimal-esg.png"), "white minimal ESG generated hero should be excluded from the slider");
assert(refreshCss.includes("hero-dark-carbon-trading.png"), "dark carbon trading generated hero should be wired into the slider");
assert(refreshCss.includes("hero-nature-technology-fusion.png"), "nature technology generated hero should be wired into the slider");
assert((html.match(/data-section-indicator=/g) || []).length >= 12, "each non-hero section indicator should expose section navigation controls");
assert((html.match(/data-section-next/g) || []).length >= 4, "indicator arrows should expose next-section controls");
assert(script.includes("heroIndicatorDots"), "hero indicators should be handled separately from section indicators");
assert(script.includes("sectionIndicatorDots"), "section indicators should be wired to section navigation");
assert(script.includes("scrollToSection"), "indicator controls should scroll to target sections");
assert(/\.hero-copy\s*\{[\s\S]*?transform:\s*translateY\(30px\)/.test(refreshCss), "hero copy should sit slightly lower to balance the hero visual weight");
assert(/@media \(max-width:\s*760px\)[\s\S]*?\.hero-copy\s*\{[\s\S]*?transform:\s*none/.test(refreshCss), "hero copy offset should be removed on mobile");
assert(/\.market-section-inner\s*\{[\s\S]*?min-height:\s*calc\(100svh - var\(--header-h\)\)/.test(refreshCss), "market section content should use viewport height minus header for vertical centering");
assert(/\.market-section-inner\s*\{[\s\S]*?align-content:\s*center/.test(refreshCss), "market section content should be vertically centered");
assert(html.includes("./assets/carbon-i-transparent-logo.svg"), "shared header logo should be bundled inside the site assets folder");
assert(/\.site-header\s+\.brand\s+img\s*\{[\s\S]*?filter:/.test(refreshCss), "light header logo should be theme-adjusted with a filter");
assert(/\.site-header\.is-header-dark\s+\.brand\s+img\s*\{[\s\S]*?filter:\s*none/.test(refreshCss), "dark header logo should use the white transparent logo without filter");
assert(html.includes("primary-nav primary-nav--aligned-mega"), "main header should use the aligned mega menu variant");
assert(html.includes("aligned-mega-panel"), "main header should include an aligned full-width submenu panel");
assert(html.includes('data-mega-target="forecast"') && html.includes('data-mega-group="forecast"'), "forecast main menu should connect to its submenu group");
assert(html.includes('data-mega-target="data"') && html.includes('data-mega-group="data"'), "data main menu should connect to its submenu group");
assert(html.includes('data-mega-target="report"') && html.includes('data-mega-group="report"'), "report main menu should connect to its submenu group");
assert(html.includes('data-mega-target="policy"') && html.includes('data-mega-group="policy"'), "policy main menu should connect to its submenu group");
assert(html.includes("가격동향") && html.includes("거래동향") && html.includes("KOC 발행현황"), "data submenu should include requested items");
assert(html.includes("동향보고서") && html.includes("전망보고서") && html.includes("세미나 리뷰"), "report submenu should include requested two-depth items");
assert(/\.primary-nav--aligned-mega\s*\{[\s\S]*?grid-template-columns:\s*repeat\(4,\s*var\(--mega-column-width\)\)/.test(refreshCss), "main menu should use four equal-width columns");
assert(/\.primary-nav--aligned-mega\s*>\s*a::after\s*\{[\s\S]*?content:\s*none\s*!important/.test(refreshCss), "aligned mega menu should not duplicate the hover underline bar");
assert(/\.aligned-mega-group\s*\{[\s\S]*?left:\s*var\(--mega-group-left/.test(refreshCss), "submenu groups should be positioned from the computed main menu coordinates");
assert(/\.aligned-mega-group\s*\{[\s\S]*?bottom:\s*0/.test(refreshCss), "selected submenu column background should reach the bottom of the panel");
assert(/\.aligned-mega-group\s*\{[\s\S]*?padding:\s*28px 16px 72px/.test(refreshCss), "submenu content should keep generous bottom breathing room inside the selected background");
assert(/\.aligned-mega-group::before\s*\{[\s\S]*?height:\s*1px/.test(refreshCss), "connected submenu highlight bar should be a subtle 1px line");
assert(!refreshCss.includes("box-shadow: inset 0 3px 0 var(--color-primary-link)"), "connected submenu highlight should not use a thick 3px bar");
assert(/\.aligned-mega-group a\s*\{[\s\S]*?font-weight:\s*500\s*!important/.test(refreshCss), "last-depth submenu links should stay visually lighter than headings");
assert(script.includes("syncAlignedMegaColumns"), "submenu groups should sync to actual main menu link positions");
assert(script.includes("--mega-group-left") && script.includes("--mega-group-width"), "submenu alignment should use computed CSS variables");
assert(refreshCss.includes('.site-header:has([data-mega-target="data"]:hover) [data-mega-group="data"]'), "hovering a main menu should highlight its connected submenu group");
assert(refreshCss.includes('.site-header:has([data-mega-group="data"]:hover) [data-mega-target="data"]'), "hovering a submenu group should highlight its connected main menu");
assert(/\.hero-section\s+\.indicator-dot\s*\{[\s\S]*?background:\s*rgba\(255,\s*255,\s*255,\s*0\.58\)/.test(refreshCss), "hero indicator dots should be bright enough on dark backgrounds");
assert(/\.hero-section\s+\.indicator-arrow\s*\{[\s\S]*?color:\s*rgba\(255,\s*255,\s*255,\s*0\.92\)/.test(refreshCss), "hero indicator arrow should be bright enough on dark backgrounds");
assert(!html.includes("<footer class=\"hero-footer\">"), "hero actions should not be isolated in a separate footer bar");
assert(html.includes("hero-floating-actions"), "hero should include integrated floating inquiry actions");
assert(/\.hero-floating-button:hover[\s\S]*?transform:\s*translateY\(-2px\)/.test(refreshCss), "hero floating buttons should provide a refined hover interaction");
assert(/\.hero-floating-button:active[\s\S]*?transform:\s*translateY\(0\)/.test(refreshCss), "hero floating buttons should provide an active state");
assert(/\.menu-button\s*\{[\s\S]*?border:\s*0\s*!important[\s\S]*?background:\s*transparent\s*!important/.test(refreshCss), "menu button should use a transparent no-border hamburger style");
assert(/\.menu-button span\s*\{[\s\S]*?width:\s*20px\s*!important[\s\S]*?height:\s*2px/.test(refreshCss), "menu button bars should keep a compact 20px visual size");
assert(/\.hero-copy,\s*\.market-menu,[\s\S]*?opacity:\s*1;[\s\S]*?transform:\s*none;/.test(refreshCss), "customer-facing content should be visible immediately without relying on reveal timing");
assert(/@media \(max-width:\s*760px\)[\s\S]*?\.primary-nav\s*\{[\s\S]*?display:\s*none\s*!important/.test(refreshCss), "mobile header should not expose desktop mega menu labels");
assert(/@media \(max-width:\s*760px\)[\s\S]*?\.hero-inner\s*\{[\s\S]*?flex-direction:\s*column\s*!important/.test(refreshCss), "mobile hero should stack copy and menu content vertically");
assert(html.includes("data-theme-demo"), "theme demo markup should remain available for internal review");
assert(/\.theme-demo\s*\{[\s\S]*?display:\s*none\s*!important/.test(refreshCss), "temporary theme demo toggle should be hidden for customer sharing");
assert((html.match(/data-theme-option=/g) || []).length === 10, "theme demo should provide ten theme options");
assert(html.includes("data-theme-opacity"), "theme demo should include a background motif opacity control");
assert(html.includes('min="0" max="100" value="30" data-theme-opacity'), "background motif control should default to 30% and allow zero to make motifs fully transparent");
assert(html.includes("data-theme-bg-opacity"), "theme demo should include a near-white background color opacity control");
assert(html.includes('min="0" max="35" value="12" data-theme-bg-opacity'), "background color control should start lightly tinted and allow zero to resolve to white");
assert(refreshCss.includes("body.theme-eco-emerald"), "eco emerald theme should be defined");
assert(refreshCss.includes("body.theme-data-blue"), "data blue theme should be defined");
assert(refreshCss.includes("body.theme-graphite-gold"), "graphite gold theme should be defined");
assert(refreshCss.includes("body.theme-clean-teal"), "clean teal theme should be defined");
assert(refreshCss.includes("body.theme-institutional-blue"), "institutional blue theme should be defined");
assert(refreshCss.includes("body.theme-climate-slate"), "climate slate theme should be defined");
assert(refreshCss.includes("body.theme-forest-graphite"), "forest graphite theme should be defined");
assert(refreshCss.includes("body.theme-carbon-aqua"), "carbon aqua theme should be defined");
assert(refreshCss.includes("body.theme-report-neutral"), "report neutral theme should be defined");
assert(refreshCss.includes("--theme-news-motif"), "themes should define a news section background motif");
assert(refreshCss.includes("--theme-service-motif"), "themes should define a service section background motif");
assert(!refreshCss.includes("repeating-linear-gradient"), "theme motifs should not use grid-like repeated straight lines");
assert(refreshCss.includes("translate(68 90) rotate(18"), "service motifs should use bounded organic SVG outlines that do not cut at section edges");
assert(!refreshCss.includes("overflow: visible !important"), "theme motif fix should not create a second page scrollbar");
assert(!refreshCss.includes("inset: -24vh 0"), "theme motif layer should not extend document height");
assert(!refreshCss.includes("translate(-310 -118)"), "news motif should not rely on clipped off-canvas shapes");
assert(!refreshCss.includes("translate(1042 -160)"), "service motif should not rely on clipped off-canvas shapes");
assert(/\.news-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)\s+calc\(50% \+ 150px\)\s+center\s*\/\s*130% 130%/.test(refreshCss), "news section should reuse the service motif for the v3_codex_c experiment");
assert(/\.service-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)\s+calc\(50% \+ 150px\)\s+center\s*\/\s*130% 130%/.test(refreshCss), "service motif should be enlarged and biased right for the v3_codex_a experiment");
assert(/\.news-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)/.test(refreshCss), "news section should use the service theme motif as a solid mask");
assert(/\.service-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)/.test(refreshCss), "service section should use the active theme motif as a solid mask");
assert(refreshCss.includes("--theme-bg-user-opacity"), "background motif opacity should be adjustable through a CSS variable");
assert(refreshCss.includes("--theme-section-bg-opacity"), "section background color opacity should be adjustable through a CSS variable");
assert(refreshCss.includes("calc(1 - var(--theme-section-bg-opacity))"), "section background tint should invert the slider so zero is white");
assert(/\.theme-demo-panel\s*\{[\s\S]*?max-height:\s*min\(540px,\s*72vh\)/.test(refreshCss), "theme demo panel should stay usable with ten options");
assert(script.includes("applyThemeDemo"), "theme demo should be wired in JavaScript");
assert(script.includes("themeOpacityInput"), "theme motif opacity control should be wired in JavaScript");
assert(script.includes("themeBgOpacityInput"), "theme background color opacity control should be wired in JavaScript");

console.log("layout regression checks passed");
