const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert");

const root = __dirname;
const css = fs.readFileSync(path.join(root, "content-sections.css"), "utf8");
const refreshCss = fs.readFileSync(path.join(root, "design-refresh.css"), "utf8");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const script = fs.readFileSync(path.join(root, "script.js"), "utf8");

const newsSectionBlock = css.match(/\.news-section\s*\{[^}]*\}/)?.[0] || "";
const pageIndicatorBlock = refreshCss.match(/\.page-indicator\s*\{[^}]*\}/)?.[0] || "";

assert(!/height:\s*100s?vh/.test(newsSectionBlock), "news section must not be fixed to the viewport height");
assert(/\.content-section\s*\{[^}]*overflow:\s*visible/s.test(css), "content sections should allow oversized content to remain visible");
assert(script.includes("canScrollWithinCurrentSection"), "wheel snapping should allow normal scroll inside oversized sections");
assert(!/display:\s*none\s*!important/.test(pageIndicatorBlock), "page indicators should remain visible for hero slide and section orientation");
assert(/scroll-snap-type:\s*y\s+mandatory/.test(refreshCss), "full-page vertical snap scrolling should remain enabled");
assert(/const enableSectionSnap\s*=\s*true/.test(script), "section snap wheel controller should remain enabled");
assert(/\.hero-copy(?:\s+h1)?[\s\S]*?color:\s*(?:#fff|#ffffff|var\(--color-page\))/.test(refreshCss), "hero copy should use a light color on the dark image background");
assert(/\.group-heading\s+h2[\s\S]*?color:\s*(?:#fff|#ffffff|var\(--color-page\))/.test(refreshCss), "hero menu group titles should use a light color on glass cards");
assert(/\.group-heading\s*\{[\s\S]*?border-color:\s*transparent/.test(refreshCss), "hero menu group headings should be visually distinct from clickable menu cards");
assert(/\.group-heading\s*\{[\s\S]*?box-shadow:\s*none/.test(refreshCss), "hero menu group headings should not use the same button-like shadow as menu cards");
assert((html.match(/class="hero-bg/g) || []).length === 7, "hero slider should keep the existing 3 images and add 4 selected generated images");
assert((html.match(/data-hero-indicator=/g) || []).length === 7, "hero slide indicators should match all 7 hero backgrounds");
assert(refreshCss.includes("hero-deep-green-sustainability.png"), "deep green generated hero should be wired into the slider");
assert(refreshCss.includes("hero-blue-data-intelligence.png"), "blue data generated hero should be wired into the slider");
assert(!refreshCss.includes("hero-white-minimal-esg.png"), "white minimal ESG generated hero should be excluded from the slider");
assert(refreshCss.includes("hero-dark-carbon-trading.png"), "dark carbon trading generated hero should be wired into the slider");
assert(refreshCss.includes("hero-nature-technology-fusion.png"), "nature technology generated hero should be wired into the slider");
assert((html.match(/data-section-indicator=/g) || []).length >= 12, "each non-hero section indicator should expose section navigation controls");
assert((html.match(/data-section-next/g) || []).length >= 4, "indicator arrows should expose next-section controls");
assert(script.includes("heroIndicatorDots"), "hero indicators should be handled separately from section indicators");
assert(script.includes("sectionIndicatorDots"), "section indicators should be wired to section navigation");
assert(script.includes("scrollToSection"), "indicator controls should scroll to target sections");
assert(/\.market-section-inner\s*\{[\s\S]*?min-height:\s*calc\(100svh - var\(--header-h\)\)/.test(refreshCss), "market section content should use viewport height minus header for vertical centering");
assert(/\.market-section-inner\s*\{[\s\S]*?align-content:\s*center/.test(refreshCss), "market section content should be vertically centered");
assert(html.includes("./assets/carbon-i-transparent-logo.svg"), "shared header logo should be bundled inside the site assets folder");
assert(/\.site-header\s+\.brand\s+img\s*\{[\s\S]*?filter:/.test(refreshCss), "light header logo should be theme-adjusted with a filter");
assert(/\.site-header\.is-header-dark\s+\.brand\s+img\s*\{[\s\S]*?filter:\s*none/.test(refreshCss), "dark header logo should use the white transparent logo without filter");
assert(/\.hero-section\s+\.indicator-dot\s*\{[\s\S]*?background:\s*rgba\(255,\s*255,\s*255,\s*0\.58\)/.test(refreshCss), "hero indicator dots should be bright enough on dark backgrounds");
assert(/\.hero-section\s+\.indicator-arrow\s*\{[\s\S]*?color:\s*rgba\(255,\s*255,\s*255,\s*0\.92\)/.test(refreshCss), "hero indicator arrow should be bright enough on dark backgrounds");
assert(!html.includes("<footer class=\"hero-footer\">"), "hero actions should not be isolated in a separate footer bar");
assert(html.includes("hero-floating-actions"), "hero should include integrated floating inquiry actions");
assert(/\.hero-floating-button:hover[\s\S]*?transform:\s*translateY\(-2px\)/.test(refreshCss), "hero floating buttons should provide a refined hover interaction");
assert(/\.hero-floating-button:active[\s\S]*?transform:\s*translateY\(0\)/.test(refreshCss), "hero floating buttons should provide an active state");
assert(html.includes("data-theme-demo"), "theme demo markup should remain available for internal review");
assert(/\.theme-demo\s*\{[\s\S]*?display:\s*none\s*!important/.test(refreshCss), "temporary theme demo toggle should be hidden for customer sharing");
assert((html.match(/data-theme-option=/g) || []).length === 10, "theme demo should provide ten theme options");
assert(html.includes("data-theme-opacity"), "theme demo should include a background motif opacity control");
assert(html.includes('min="0" max="100" value="30" data-theme-opacity'), "background motif control should default to 30% and allow zero to make motifs fully transparent");
assert(html.includes("data-theme-bg-opacity"), "theme demo should include a near-white background color opacity control");
assert(html.includes('min="0" max="35" value="12" data-theme-bg-opacity'), "background color control should start lightly tinted and allow zero to resolve to white");
assert(refreshCss.includes("body.theme-eco-emerald"), "eco emerald theme should be defined");
assert(refreshCss.includes("body.theme-data-blue"), "data blue theme should be defined");
assert(refreshCss.includes("body.theme-graphite-gold"), "graphite gold theme should be defined");
assert(refreshCss.includes("body.theme-clean-teal"), "clean teal theme should be defined");
assert(refreshCss.includes("body.theme-institutional-blue"), "institutional blue theme should be defined");
assert(refreshCss.includes("body.theme-climate-slate"), "climate slate theme should be defined");
assert(refreshCss.includes("body.theme-forest-graphite"), "forest graphite theme should be defined");
assert(refreshCss.includes("body.theme-carbon-aqua"), "carbon aqua theme should be defined");
assert(refreshCss.includes("body.theme-report-neutral"), "report neutral theme should be defined");
assert(refreshCss.includes("--theme-news-motif"), "themes should define a news section background motif");
assert(refreshCss.includes("--theme-service-motif"), "themes should define a service section background motif");
assert(!refreshCss.includes("repeating-linear-gradient"), "theme motifs should not use grid-like repeated straight lines");
assert(refreshCss.includes("translate(70 28) rotate(-12"), "news motifs should use bounded organic SVG outlines that do not cut at section edges");
assert(!refreshCss.includes("overflow: visible !important"), "theme motif fix should not create a second page scrollbar");
assert(!refreshCss.includes("inset: -24vh 0"), "theme motif layer should not extend document height");
assert(!refreshCss.includes("translate(-310 -118)"), "news motif should not rely on clipped off-canvas shapes");
assert(!refreshCss.includes("translate(1042 -160)"), "service motif should not rely on clipped off-canvas shapes");
assert(/\.news-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-news-motif\)\s+calc\(50% - 150px\)\s+center\s*\/\s*130% 130%/.test(refreshCss), "news motif should be enlarged and biased left for the v3_codex_a experiment");
assert(/\.service-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)\s+calc\(50% \+ 150px\)\s+center\s*\/\s*130% 130%/.test(refreshCss), "service motif should be enlarged and biased right for the v3_codex_a experiment");
assert(/\.news-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-news-motif\)/.test(refreshCss), "news section should use the active theme motif as a solid mask");
assert(/\.service-section::before\s*\{[\s\S]*?mask:\s*var\(--theme-service-motif\)/.test(refreshCss), "service section should use the active theme motif as a solid mask");
assert(refreshCss.includes("--theme-bg-user-opacity"), "background motif opacity should be adjustable through a CSS variable");
assert(refreshCss.includes("--theme-section-bg-opacity"), "section background color opacity should be adjustable through a CSS variable");
assert(refreshCss.includes("calc(1 - var(--theme-section-bg-opacity))"), "section background tint should invert the slider so zero is white");
assert(/\.theme-demo-panel\s*\{[\s\S]*?max-height:\s*min\(540px,\s*72vh\)/.test(refreshCss), "theme demo panel should stay usable with ten options");
assert(script.includes("applyThemeDemo"), "theme demo should be wired in JavaScript");
assert(script.includes("themeOpacityInput"), "theme motif opacity control should be wired in JavaScript");
assert(script.includes("themeBgOpacityInput"), "theme background color opacity control should be wired in JavaScript");

console.log("layout regression checks passed");
